### ISSUE TITLE
FFN updated and broke this after all this time

### ISSUE THREAD

**Issue by thinkpad4** [CLPeters/DeFFNetIzer#2]
@CLPeters If you are still around PLEASE update this for the changes FFN made lately

**Comment by CLPeters** [comment]
I’m sorry to have to inform you that Chad passed away suddenly on March 27
of this y ear.  I am a friend overseeing his email but I know nothing of
programming.



*From:* Thinkpad4 <notifications@github.com>
*Sent:* Saturday, December 19, 2020 11:38 PM
*To:* CLPeters/DeFFNetIzer <DeFFNetIzer@noreply.github.com>
*Cc:* Chad Peterson <chad@clpnetworks.com>; Mention <
mention@noreply.github.com>
*Subject:* [CLPeters/DeFFNetIzer] FFN updated and broke this after all this
time (#2)



@CLPeters <https://github.com/CLPeters> If you are still around PLEASE
update this for the changes FFN made lately

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CLPeters/DeFFNetIzer/issues/2>, or unsubscribe

**Comment by thinkpad4** [comment]
Oh damn, I'm sorry to hear that.   Thank you for letting me know
